### ISSUE TITLE
홈화면 로고 클릭시 상단으로 스크롤

### ISSUE THREAD

**Issue by Lewisofcroar** [Croar-Creative/pr6-frontend#11]
메인 홈화면에서 아래로 스크롤 되어있을때
좌상단과 푸터 로고 클릭시 홈화면 최상단으로 스크롤

**Comment by ho991217** [comment]
기존 기능은 홈화면으로 이동인데
홈화면으로 이동 후 -> 최상단으로 이동 인가요?
