### ISSUE TITLE
윈도우 환경에서 네비게이션 바 호버링 인터렉션 관련 이슈

### ISSUE THREAD

**Issue by Lewisofcroar** [Croar-Creative/pr6-frontend#14]
일부 윈도우 환경에서 네비게이션 바 호버링시 언더바 인터렉션이 표시 되지 않는 현상 발견됨.
윈도우10 / 크롬 환경, 일부 기능 비활성화 여부 확인되지 않음.
해당 환경에서의 정상 작동 여부 확인이 필요해보임

**Comment by ho991217** [comment]
@Lewisofcroar 확인되지 않습니다.
운영체제 버전 정보와 브라우저 정보 첨부 부탁드립니다.
